name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
            MYSQL_DATABASE: uweb_test
            MYSQL_USER: stef
            MYSQL_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run uweb3 unittests
      run: |
        python3 -m unittest test.test_model
        python3 -m unittest test.test_request
        python3 -m unittest test.test_templateparser
